In [1]:
# numpy module 
import numpy as np

In [ ]:
# function array(): use to convert the sequence into ndarray

arr = np.array([2, 5, 6, 7])
print(arr)

In [28]:
# reshape(): 
arr = np.array([2, 4, 6, 7, 8, 8])
out = arr.reshape(1, 6)
print(arr)
print(out)

[2 4 6 7 8 8]
[[2 4 6 7 8 8]]


In [36]:
# arange()
# ls = range(1, 10, 3.5)  # error 
arr = np.arange(0, 10.5, 2.5)

out = arr // 5
print(arr)
print(out)

# ls = [4, 7, 99]
# out = ls + 5  # error
# print(out)

[ 0.   2.5  5.   7.5 10. ]
[0. 0. 1. 1. 2.]


In [15]:
# sin()
arr = np.arange(10, 20)
out = np.sin(arr)
print(out)

[-0.54402111 -0.99999021 -0.53657292  0.42016704  0.99060736  0.65028784
 -0.28790332 -0.96139749 -0.75098725  0.14987721]


In [20]:
num = np.random.randint(1, 3)
print(num)

1


In [18]:
arr = np.array([3, 65, 6, 90])
k = arr.max()
print(k)

90


In [39]:
# sum
arr = np.arange(1, 13).reshape(4, 3)
out = np.sum(arr, 1)
print(arr)
print(out)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 6 15 24 33]
