In [2]:
import numpy as np

ls1 = [[1, 2, 4], [0, 1, 0]]
ls2 = [[2, 55, 7], [1, 4, 7]]

arr1 = np.array(ls1)
arr2 = np.array(ls2)

# addition of two matrix 
if arr1.shape == arr2.shape:
    # out = arr1 + arr2
    out = np.add(arr1, arr2)
else:
    print('Not Valid Matrix for Addition')    

print(arr1)
print(arr2, end='\n\n')
print(out)

# ishan - 9179199191


[[1 2 4]
 [0 1 0]]
[[ 2 55  7]
 [ 1  4  7]]

[[ 3 57 11]
 [ 1  5  7]]


In [8]:
import numpy as np

ls1 = [[1, 2, 4], [0, 1, 0]]
ls2 = [[2, 55, 7], [1, 4, 7]]

arr1 = np.array(ls1)
arr2 = np.array(ls2)
arr2.shape = 3, 2
# multiplication of two matrix 
if arr1.shape[-1] == arr2.shape[0]:
    # out = arr1 + arr2
    out = np.dot(arr1, arr2)
else:
    print('Not Valid Matrix for Addition')    

print(arr1)
print(arr2, end='\n\n')
print(out)

[[1 2 4]
 [0 1 0]]
[[ 2 55]
 [ 7  1]
 [ 4  7]]

[[32 85]
 [ 7  1]]


In [5]:
arr1.shape

(2, 3)

In [4]:
ls1 = [[1, 2, 4], [0, 1, 0]]
ls2 = [[2, 55, 7], [1, 4, 7]]

r1 = len(ls1)
c1 = len(ls1[0])
r2 = len(ls2)
c2 = len(ls2[0])

out = []
if [r1, c1] == [r2, c2]:
    for i in range(r1):
        tmp = []
        for j in range(c1):
            tmp.append(ls1[i][j] + ls2[i][j])
        out.append(tmp)    
else:
    print('Not valid matrix') 


print(ls1)
print(ls2)
print(out)

[[1, 2, 4], [0, 1, 0]]
[[2, 55, 7], [1, 4, 7]]
[[3, 57, 11], [1, 5, 7]]
