In [16]:
# Numerical Python 
import numpy as np

In [23]:
# array()

lst = [260, 5, 6, 86, -1, 11]
print(lst, type(lst))
arr = np.array(lst, dtype='uint8')
print(arr, type(arr))


[260, 5, 6, 86, -1, 11] <class 'list'>
[  4   5   6  86 255  11] <class 'numpy.ndarray'>


In [24]:
lst = [[2, 5], [11, 67]]
narr = np.array(lst)
print(narr)

[[ 2  5]
 [11 67]]


In [26]:
narr.shape

(2, 2)

In [6]:
arr.ndim

1

In [11]:
arr.shape = 2, 3
arr 

array([[ 1,  3,  4],
       [ 5,  7, 40]])

In [15]:
out = arr.reshape(2, 3)
print(out)

[[ 1  3  4]
 [ 5  7 40]]


In [4]:
lst = [[[1], [2]], [[3], [6]]]
ele = lst[0][1]
print(ele)

2


In [7]:
import numpy as np
lst = [255, 257, 7, 4, 43]
print(lst)
arr = np.array(lst, dtype='uint8')
print(arr)

[255, 257, 7, 4, 43]
[255   1   7   4  43]
