In [2]:
# read array from user 
import numpy as np
lst = list(map(eval, input().split()))  # ['3', '4', '5', '75', '-56']
arr = np.array(lst, dtype='float')
lst.reverse()
arr = arr[::-1]
print(lst)
print(arr)

[8, -1, 6, 3]
[ 8. -1.  6.  3.]


In [ ]:
# You are given a space separated list of nine integers. 
# Your task is to convert this list into 3x3 numpy array
import numpy as np
lst = list(map(eval, input().split()))  # ['3', '4', '5', '75', '-56']
arr = np.array(lst).reshape(3, 3)
print(arr)

In [6]:
# shape and reshape()

arr = np.array([3, 5, 7, 8])
tre = arr.reshape(2, 2)
arr.shape = 2, 2
print(arr)

[[3 5]
 [7 8]]


In [7]:
'''Your task is to print an array of size NxM with its main diagonal 
elements as 1’s and 0’s everywhere else'''
M, N = map(int, input().split())  # '3 3'
arr = np.eye(M, N)
print(arr)


[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
import numpy as np
n,m = map(int, input().split())
lst1 = list(map(int, input().split()))
lst2 = list(map(int, input().split()))
arr1 = np.array(lst1).reshape(n,m)
arr2 = np.array(lst2).reshape(n,m)
multiply = arr1*arr2
addition = np.add(arr1,arr2)
subtract = np.subtract(arr1,arr2)
power = arr1**arr2
modulus = arr1%arr2
print(multiply)
print(addition)
print(subtract)
print(power)
print(modulus)


In [2]:
import numpy as np
arr1 = np.arange(1, 13)
print(arr1)
arr1.shape= (3, 4)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
